# This is a basic workflow that is manually triggered

name: Peter manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
    targetEnv: prod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.SPSECRET }}
  
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.9
      with:
        # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
        scope: resourcegroup
        # Override the Subscription Id set by Azure Login.
        subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
        # Provide the name of a resource group, only required for resource Group deployments.
        resourceGroupName: pcl-rg
        # Specify the path or URL to the Azure Resource Manager template.
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webAppName=p23021devops-${{ env.targetEnv }}
        deploymentName: github-webapp
    
